kitting_phase2_logger:
    base_directory: "~/kitting_bags"
    object_name: "default_object"
    auto_stop_on_contact: false
    export_csv_on_stop: true
    topics_to_record:
        - /kitting_state_controller/kitting_state_data
        - /kitting_phase2/state
        - /kitting_phase2/record_control
        - /joint_states
